In [1]:
# Importing important Libraries
import selenium
import pandas as pd
from selenium import webdriver
import time
# Importing required Exceptions which needs to handled
from selenium.common.exceptions import StaleElementReferenceException, NoSuchElementException

In [2]:
# Activating the chrome browser and Opening the homepage of images.google.com
driver = webdriver.Chrome('chromedriver.exe')
driver.get('https://www.cars24.com/buy-used-car/?sort=P&storeCityId=132&pinId=201001')

In [3]:
# 500 time we scroll down by 10000 in order to generate more images on the website
for _ in range(500):
    driver.execute_script("window.scrollBy(0,10000)")

In [4]:
#Make empty lists  
car_Brand=[]
car_owner=[]
car_kilometers=[]
car_fuel_type=[]
car_registration=[]
car_price=[]
car_model=[]
car_transmission=[]
# Extracting Brand from xpath
try:
    for i in driver.find_elements_by_xpath("//h2[@class='_3FpCg']"):
        car_Brand.append(i.text)
except NoSuchElementException:
    car_Brand.append("_")
        
# Extracting Name from xpath
try:
    for i in driver.find_elements_by_xpath("//div[@class='_1l4fi']/ul/li[2]"):
        car_owner.append(i.text)
except NoSuchElementException:
    car_owner.append('-')
    
# Extracting colour from xpath
try:
    for i in driver.find_elements_by_xpath("//div[@class='_1l4fi']/ul/li[1]"):
        car_kilometers.append(i.text)
except NoSuchElementException:
    car_kilometers.append('-')
    
    
# Extracting colour from xpath
try:
    for i in driver.find_elements_by_xpath("//p[@class='cvakB']/span"):
        car_transmission.append(i.text)
except NoSuchElementException:
    car_transmission.append('-')
    
# Extracting Name from xpath
try:
    for i in driver.find_elements_by_xpath("//div[@class='_1l4fi']/ul/li[3]"):
        car_fuel_type.append(i.text)
except NoSuchElementException:
    car_fuel_type.append('-')
    
# Extracting Name from xpath
try:
    for i in driver.find_elements_by_xpath("//p[@class='cvakB']"):
        car_model.append(i.text)
except NoSuchElementException:
    car_model.append('-')        
        
# Extracting colour from xpath
try:
    for i in driver.find_elements_by_xpath("//div[@class='_19zc5']/div[2]"):
        car_price.append(i.text)
except NoSuchElementException:
    car_price.append('-')

In [95]:
Car=pd.DataFrame({})
Car["car_Brand"]=car_Brand
Car["car_owner"]=car_owner
Car["car_kilometers"]=car_kilometers
Car["car_fuel_type"]=car_fuel_type
Car["car_transmission"]=car_transmission
Car["car_model"]=car_model
Car["car_price"]=car_price
Car

,car_Brand,car_owner,car_kilometers,car_fuel_type,car_transmission,car_model,car_price
0,2020 Maruti Baleno,1st Owner,"3,920 km",Petrol,Manual,DELTA 1.2 K12 Manual,"₹6,45,199"
1,2020 Maruti Baleno,1st Owner,"5,645 km",Petrol,Manual,SIGMA 1.2 K12 Manual,"₹5,74,999"
2,2014 Maruti Alto 800,1st Owner,"12,535 km",Petrol,Manual,VXI Manual,"₹2,93,599"
3,2019 Renault TRIBER,1st Owner,"7,704 km",Petrol,Manual,1.0 RXL PETROL Manual,"₹4,73,499"
4,2021 Hyundai VENUE,1st Owner,"2,589 km",Petrol,,S MT 1.2 KAPPA,"₹7,94,699"
...,...,...,...,...,...,...,...
2794,2016 Hyundai Elite i20,1st Owner,"1,29,194 km",Diesel,Manual,SPORTZ 1.4 Manual,"₹5,72,499"
2795,2014 Hyundai Verna,3rd Owner,"1,86,575 km",Diesel,Manual,FLUIDIC 1.6 SX CRDI Manual,"₹3,63,299"
2796,2020 Maruti Baleno,1st Owner,"10,126 km",Petrol,Manual,DELTA 1.2 K12 Manual,"₹6,45,799"
2797,2011 Hyundai i20,2nd Owner,"61,798 km",Petrol,Manual,ASTA 1.2 Manual,"₹2,30,699"
2798,2012 Mitsubishi Pajero Sport,1st Owner,"1,40,976 km",Diesel,Automatic,2.5 MT 4X4 Automatic,"₹5,56,599"

In [96]:
# saving the dataframe
Car.to_csv('FristCar24.csv')